/* ============================================================
   ÉLUME — Catalogue produits
   ============================================================ */
const PRODUCTS = [
  /* ── ROBES ── */
  {
    id: 1,
    name: "Robe Midi Fleurie",
    price: 89,
    originalPrice: 119,
    category: "robes",
    colors: ["#e8a090","#8eb4c8","#b8d4b0"],
    colorNames: ["Terracotta","Ciel","Sauge"],
    sizes: ["XS","S","M","L","XL"],
    badge: "Promo",
    rating: 4.5, reviews: 124,
    bg: "linear-gradient(145deg,#f5c0a8 0%,#e8907a 100%)",
    description: "Une robe midi légère à imprimé fleuri subtil. Idéale pour les journées ensoleillées, elle se porte aussi bien avec des sandales qu'avec des bottines en demi-saison. Coupe ajustée à la taille avec une légère évasée en bas.",
    details: ["Composition : 100% viscose","Doublure : non doublée","Entretien : lavage machine 30°","Fabriquée au Portugal"]
  },
  {
    id: 2,
    name: "Robe Portefeuille Satin",
    price: 119,
    originalPrice: null,
    category: "robes",
    colors: ["#2d3a4a","#8b6f5e","#c8b89a"],
    colorNames: ["Nuit","Cognac","Sable"],
    sizes: ["XS","S","M","L"],
    badge: "Nouveau",
    rating: 4.8, reviews: 57,
    bg: "linear-gradient(145deg,#3a4a60 0%,#1e2a38 100%)",
    description: "La robe portefeuille en satin mat qui s'adapte à toutes les morphologies. Son col V croisé et sa ceinture à nouer offrent une silhouette flatteuse. Parfaite du bureau au dîner.",
    details: ["Composition : 97% polyester, 3% élasthanne","Effet satin mat","Entretien : lavage délicat 30°","Longueur : 110 cm (taille 38)"]
  },
  {
    id: 3,
    name: "Robe de Soirée Longue",
    price: 195,
    originalPrice: null,
    category: "robes",
    colors: ["#1a1a2e","#4a3060","#8b2252"],
    colorNames: ["Noir","Prune","Bordeaux"],
    sizes: ["S","M","L","XL"],
    badge: null,
    rating: 4.7, reviews: 39,
    bg: "linear-gradient(145deg,#2a1a3e 0%,#1a0a2e 100%)",
    description: "Robe longue fluide pour les grandes occasions. Encolure dos nu, bretelles fines réglables. Le tissu crêpe tombe parfaitement et résiste aux froissements.",
    details: ["Composition : 100% polyester recyclé","Fermeture : zip invisible","Longueur : 140 cm (taille 38)","Collection capsule soirée"]
  },
  {
    id: 4,
    name: "Robe Chemise Lin",
    price: 75,
    originalPrice: null,
    category: "robes",
    colors: ["#e8e0d0","#c8b4a0","#a09080"],
    colorNames: ["Ecru","Lin","Taupe"],
    sizes: ["XS","S","M","L","XL","XXL"],
    badge: null,
    rating: 4.3, reviews: 88,
    bg: "linear-gradient(145deg,#ede5d5 0%,#cfc0ae 100%)",
    description: "La robe chemise en lin pur, emblème de l'élégance décontractée. Boutons nacre, poches latérales, col classique. Portée ouverte sur un jean ou fermée en robe.",
    details: ["Composition : 100% lin lavé","Lisse avec le temps","Entretien : lavage machine 40°","Origine : France"]
  },

  /* ── TOPS ── */
  {
    id: 5,
    name: "Top en Lin Brodé",
    price: 45,
    originalPrice: 59,
    category: "tops",
    colors: ["#f0ebe0","#c8d8c0","#e0c8b8"],
    colorNames: ["Ecru","Menthe","Blush"],
    sizes: ["XS","S","M","L","XL"],
    badge: "Promo",
    rating: 4.4, reviews: 201,
    bg: "linear-gradient(145deg,#d8eed0 0%,#a8c8a0 100%)",
    description: "Top en lin avec broderies anglaises sur l'encolure. Coupe loose et respirante, parfaite pour l'été. Se rentre dans une jupe ou un pantalon taille haute.",
    details: ["Composition : 55% lin, 45% coton","Broderies faites main","Entretien : lavage machine 30°","Séchage à plat recommandé"]
  },
  {
    id: 6,
    name: "Chemise Oversize Oxford",
    price: 65,
    originalPrice: null,
    category: "tops",
    colors: ["#f0f0f0","#c0d0e8","#e8d8c0"],
    colorNames: ["Blanc","Bleu clair","Pêche"],
    sizes: ["XS","S","M","L","XL","XXL"],
    badge: "Nouveau",
    rating: 4.6, reviews: 143,
    bg: "linear-gradient(145deg,#d8e8f8 0%,#a8c0d8 100%)",
    description: "La chemise oversize incontournable, en coton Oxford léger. Col boutonné, manches longues retroussables. Polyvalente : portée rentrée, nouée à la taille ou comme veste.",
    details: ["Composition : 100% coton Oxford","Poids du tissu : 130g/m²","Entretien : lavage machine 40°","Coupe unisexe"]
  },
  {
    id: 7,
    name: "Top Soie Fluide",
    price: 85,
    originalPrice: null,
    category: "tops",
    colors: ["#e8c0b0","#b0c8d8","#d8e0c0"],
    colorNames: ["Rose poudré","Bleu gris","Vert amande"],
    sizes: ["XS","S","M","L"],
    badge: null,
    rating: 4.9, reviews: 67,
    bg: "linear-gradient(145deg,#f0d0c0 0%,#e0b0a0 100%)",
    description: "Top en soie naturelle à encolure ronde et manches courtes légèrement bouffantes. Le tomber irréprochable de la soie pour une tenue habillée sans effort.",
    details: ["Composition : 100% soie naturelle","Entretien : nettoyage à sec","Fabriqué en Italie","Certifié OEKO-TEX"]
  },
  {
    id: 8,
    name: "Pull Col Roulé Cachemire",
    price: 155,
    originalPrice: null,
    category: "tops",
    colors: ["#2a2a2a","#8a6a5a","#c0a888"],
    colorNames: ["Noir","Noisette","Camel"],
    sizes: ["XS","S","M","L","XL"],
    badge: null,
    rating: 4.8, reviews: 93,
    bg: "linear-gradient(145deg,#6a5848 0%,#4a3828 100%)",
    description: "Le col roulé cachemire qui traverse les saisons. Douceur incomparable, tenue parfaite au lavage. Coupe légèrement oversize pour plus de confort.",
    details: ["Composition : 100% cachemire grade A","Grammage : 2 fils","Entretien : lavage à la main 30°","Origine : Mongolie"]
  },

  /* ── PANTALONS ── */
  {
    id: 9,
    name: "Pantalon Palazzo Lin",
    price: 79,
    originalPrice: 99,
    category: "pantalons",
    colors: ["#e8e0d0","#3a3a3a","#8a7060"],
    colorNames: ["Ecru","Noir","Cognac"],
    sizes: ["34","36","38","40","42","44"],
    badge: "Promo",
    rating: 4.5, reviews: 176,
    bg: "linear-gradient(145deg,#e0d8c8 0%,#c8c0b0 100%)",
    description: "Le pantalon palazzo en lin, ultra-fluide et élégant. Taille haute avec pince, jambes larges. Tombe magnifiquement et reste frais par temps chaud.",
    details: ["Composition : 100% lin","Taille haute avec ceinture","Entretien : lavage machine 30°","Longueur : 100 cm (taille 38)"]
  },
  {
    id: 10,
    name: "Jean Slim Brut",
    price: 95,
    originalPrice: null,
    category: "pantalons",
    colors: ["#2a3848","#1a1a1a","#7a6858"],
    colorNames: ["Brut","Noir","Délavé"],
    sizes: ["25","26","27","28","29","30","31","32"],
    badge: null,
    rating: 4.4, reviews: 258,
    bg: "linear-gradient(145deg,#384858 0%,#1e2838 100%)",
    description: "Jean slim en denim brut premium. Cinq poches classiques, coupe ajustée qui se détend avec le temps. Le jean qui dure des années.",
    details: ["Composition : 98% coton, 2% élasthanne","Denim japonais selvedge","Entretien : lavage retourné 30°","Produit en Europe"]
  },
  {
    id: 11,
    name: "Pantalon Tailleur",
    price: 110,
    originalPrice: null,
    category: "pantalons",
    colors: ["#3a3a3a","#c8b8a8","#4a5060"],
    colorNames: ["Charcoal","Beige","Ardoise"],
    sizes: ["34","36","38","40","42","44"],
    badge: "Nouveau",
    rating: 4.7, reviews: 52,
    bg: "linear-gradient(145deg,#505060 0%,#303040 100%)",
    description: "Pantalon tailleur droit à pinces, coupe classique revisitée. Parfait pour le bureau comme pour les sorties. S'associe avec son blazer assorti (ref. 13).",
    details: ["Composition : 60% laine, 40% polyester","Doublure partielle","Entretien : nettoyage à sec","Fabriqué en France"]
  },
  {
    id: 12,
    name: "Short en Jean Vintage",
    price: 55,
    originalPrice: null,
    category: "pantalons",
    colors: ["#8898b0","#3a3a3a","#c0a870"],
    colorNames: ["Clair","Noir","Doré"],
    sizes: ["34","36","38","40","42"],
    badge: null,
    rating: 4.2, reviews: 114,
    bg: "linear-gradient(145deg,#98a8c0 0%,#687890 100%)",
    description: "Short en jean à effet vintage, taille haute et bords légèrement effilochés. L'essentiel de l'été à glisser dans toutes les valises.",
    details: ["Composition : 100% coton recyclé","Taille haute boutonnée","Entretien : lavage machine 30°","Produit éco-responsable"]
  },

  /* ── VESTES ── */
  {
    id: 13,
    name: "Blazer Structuré",
    price: 189,
    originalPrice: null,
    category: "vestes",
    colors: ["#2a2a2a","#c8b8a8","#4a5060"],
    colorNames: ["Noir","Beige","Ardoise"],
    sizes: ["XS","S","M","L","XL"],
    badge: "Nouveau",
    rating: 4.8, reviews: 78,
    bg: "linear-gradient(145deg,#3a3a3a 0%,#1a1a1a 100%)",
    description: "Le blazer structuré qui redéfinit l'élégance moderne. Épaulettes légères, revers crantés, deux poches passepoilées. Se porte sur tout, transforme tout.",
    details: ["Composition : 60% laine, 40% polyester","Doublure soie","Entretien : nettoyage à sec","Fabriqué en France"]
  },
  {
    id: 14,
    name: "Veste en Daim",
    price: 145,
    originalPrice: 185,
    category: "vestes",
    colors: ["#a07858","#6a4838","#3a2818"],
    colorNames: ["Camel","Cognac","Brun"],
    sizes: ["XS","S","M","L","XL"],
    badge: "Promo",
    rating: 4.6, reviews: 91,
    bg: "linear-gradient(145deg,#b89070 0%,#806050 100%)",
    description: "Veste en daim synthétique de haute qualité, souple et résistante. Col montant, fermeture zip, deux poches zippées. L'alternative éco à la veste en cuir.",
    details: ["Composition : 100% polyuréthane","Doublure 100% polyester","Entretien : essuyage humide","Sans produits d'origine animale"]
  },
  {
    id: 15,
    name: "Manteau Laine Bouclette",
    price: 275,
    originalPrice: null,
    category: "vestes",
    colors: ["#e8e0d8","#3a3a3a","#c8a8a0"],
    colorNames: ["Crème","Noir","Blush"],
    sizes: ["XS","S","M","L","XL"],
    badge: null,
    rating: 4.9, reviews: 44,
    bg: "linear-gradient(145deg,#ece8e0 0%,#d0c8c0 100%)",
    description: "Le manteau intemporel en laine bouclette, chaud et raffiné. Coupe droite mi-long, boutons en corne, poches à rabat. Un investissement mode pour de nombreuses saisons.",
    details: ["Composition : 70% laine, 30% polyamide","Doublure satin","Entretien : nettoyage à sec","Origine : Portugal"]
  },
  {
    id: 16,
    name: "Veste Bomber Satin",
    price: 115,
    originalPrice: null,
    category: "vestes",
    colors: ["#1a2a1a","#3a1a2a","#1a1a3a"],
    colorNames: ["Vert forêt","Prune","Marine"],
    sizes: ["XS","S","M","L","XL","XXL"],
    badge: "Nouveau",
    rating: 4.5, reviews: 63,
    bg: "linear-gradient(145deg,#2a4028 0%,#182818 100%)",
    description: "Bomber en satin brillant avec bandes en côtes aux poignets et à la taille. Style sport-chic, parfaite sur une robe ou un jean. La pièce statement de la saison.",
    details: ["Composition : 100% polyester satin","Doublure microfibre","Entretien : lavage machine 30°","Coupe unisexe oversize"]
  },

  /* ── ACCESSOIRES ── */
  {
    id: 17,
    name: "Sac Cabas Cuir",
    price: 185,
    originalPrice: null,
    category: "accessoires",
    colors: ["#c8a878","#3a2818","#1a1a1a"],
    colorNames: ["Camel","Cognac","Noir"],
    sizes: ["Unique"],
    badge: null,
    rating: 4.7, reviews: 109,
    bg: "linear-gradient(145deg,#d8b888 0%,#b89060 100%)",
    description: "Sac cabas en cuir pleine fleur, grand format. Deux anses courtes + bandoulière amovible. Parfait pour le quotidien, capacité pour un A4.",
    details: ["Matière : cuir pleine fleur","Doublure textile","Fermeture magnétique","Dimensions : 40×32×14 cm"]
  },
  {
    id: 18,
    name: "Ceinture Tressée",
    price: 38,
    originalPrice: null,
    category: "accessoires",
    colors: ["#c8a878","#3a2818","#1a1a1a"],
    colorNames: ["Camel","Cognac","Noir"],
    sizes: ["S/M","M/L","L/XL"],
    badge: null,
    rating: 4.3, reviews: 187,
    bg: "linear-gradient(145deg,#c8b090 0%,#a89070 100%)",
    description: "Ceinture tressée en cuir véritable, boucle dorée ajustable. S'adapte à toutes les tailles avec son système de fermeture réglable. Fini soigné.",
    details: ["Matière : cuir véritable","Boucle métal doré","Largeur : 2.5 cm","Made in Italy"]
  },
  {
    id: 19,
    name: "Écharpe Soie Imprimée",
    price: 65,
    originalPrice: null,
    category: "accessoires",
    colors: ["#e8c8a0","#a0c8d8","#d0a8c0"],
    colorNames: ["Doré","Turquoise","Mauve"],
    sizes: ["Unique"],
    badge: "Nouveau",
    rating: 4.6, reviews: 74,
    bg: "linear-gradient(145deg,#f0d0a8 0%,#d8b080 100%)",
    description: "Écharpe en soie naturelle 90×90 cm à imprimé exclusif. À nouer en ceinture, en bandeau ou simplement posée sur les épaules. Motifs revisités chaque saison.",
    details: ["Matière : 100% soie naturelle","Dimensions : 90×90 cm","Bords roulottés à la main","Impression numérique haute définition"]
  },
  {
    id: 20,
    name: "Chapeau Bob Naturel",
    price: 42,
    originalPrice: 55,
    category: "accessoires",
    colors: ["#e8d8b0","#a09070","#3a3028"],
    colorNames: ["Naturel","Sable","Brun"],
    sizes: ["S/M","M/L"],
    badge: "Promo",
    rating: 4.4, reviews: 136,
    bg: "linear-gradient(145deg,#e8d5b0 0%,#c8b890 100%)",
    description: "Bob en paille tressée naturelle, bord souple et cordon réglable intérieur. Protège du soleil avec style. Se roule dans une valise sans se déformer.",
    details: ["Matière : raphia naturel","Cordon réglable","Indice protection solaire : UPF 30","Fabriqué au Maroc"]
  }
];
